// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdates():Promise<Array<string>>;

export function GetInstallDir():Promise<string>;

export function GetServerInfo(arg1:string):Promise<main.InfoResponse>;

export function OpenLink(arg1:string):Promise<void>;

export function StartGame(arg1:string):Promise<string>;

export function UpdateFromManifest(arg1:string,arg2:string):Promise<void>;
