// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdates() {
  return window['go']['main']['App']['CheckUpdates']();
}

export function GetGameExecutable() {
  return window['go']['main']['App']['GetGameExecutable']();
}

export function GetInstallDir() {
  return window['go']['main']['App']['GetInstallDir']();
}

export function GetNews(arg1) {
  return window['go']['main']['App']['GetNews'](arg1);
}

export function GetServerInfo(arg1) {
  return window['go']['main']['App']['GetServerInfo'](arg1);
}

export function OpenLink(arg1) {
  return window['go']['main']['App']['OpenLink'](arg1);
}

export function StartGame() {
  return window['go']['main']['App']['StartGame']();
}

export function UpdateFromManifest(arg1, arg2) {
  return window['go']['main']['App']['UpdateFromManifest'](arg1, arg2);
}
